# Generated by Django 5.2.4 on 2025-08-19 12:01

import django_xchange.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                (
                    'base',
                    models.CharField(
                        default=django_xchange.models.get_base_currency, help_text='Base rate (ISO3)', max_length=3
                    ),
                ),
                ('rates', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
