name: Lint

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash
    outputs:
      run_tests: ${{ steps.changes.outputs.run_tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: changes
        name: Check for file changes
        uses: dorny/paths-filter@0bc4621a3135347011ad047f9ecf449bf72ce2bd # v3.0.0
        with:
          base: ${{ github.ref }}
          token: ${{ github.token }}
          filters: .github/file-filters.yml

  pkg_meta:
    needs: [ changes ]
    if: needs.changes.outputs.run_tests == 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Lint with flake8
        run: |
          tox -e pkg_meta
  lint:
    needs: [ changes ]
    if: needs.changes.outputs.run_tests == 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Lint with flake8
        run: |
          tox -e lint
